module.exports = {
  dir: "/opt/server-dashboard_service",
  PORT: 5000,
  certification: {
    country: "RU",
    province: "MS",
    city: "Moscow",
    org: "BeJlka Corp.",
    email: "bejlka@yandex.ru",
    ou: "IT",
  },
  servers: {
    admin: {
      description: "Админский VPN",
      code: "admin",
      logs: true,
      type: "root",
      friends: false,
      maxclients: 100,
      network: {
        host: "0.0.0.0",
        remote: "",
        internet: "10.1.0.0/24",
        port: 1194,
        mport: 2294,
        proto: "udp",
        dev: "tun0",
      },
    },
    device: {
      description: "VPN для устройств",
      code: "device",
      logs: false,
      type: "public",
      friends: true,
      maxclients: 100,
      network: {
        host: "0.0.0.0",
        remote: "",
        internet: "10.2.0.0/24",
        port: 1195,
        mport: 2295,
        proto: "udp",
        dev: "tun1",
      },
    },
    client: {
      description: "VPN для пользователей",
      code: "client",
      logs: false,
      type: "public",
      friends: false,
      maxclients: 100,
      network: {
        host: "0.0.0.0",
        remote: "",
        internet: "10.3.0.0/24",
        port: 1196,
        mport: 2296,
        proto: "udp",
        dev: "tun2",
      },
    },
  },
};
